### ISSUE TITLE
`brew file update` fails, reporting `brew list` being disabled

### ISSUE THREAD

**Issue by zcutlip** [rcmdnk/homebrew-file#101]
When I run `brew file update` or `brew-file update`, it fails after calling `brew upgrade --cask`:
```
❱ brew-file update
$ brew update
Already up-to-date.
$ brew upgrade --fetch-HEAD
$ brew upgrade --cask
Error: Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead.
[ERROR]: Failed at command: /usr/local/bin/brew list
```

**Comment by rcmdnk** [comment]
It seems the problem happens with `master` version of homebrew/brew.
The origin of the change is: https://github.com/Homebrew/brew/commit/d496f5c121f33fd91a820f60defedd0bbc01e4c2#

Related issue: https://discourse.brew.sh/t/brew-list-less-fails/9224

It shows message only when the output is passed to non-terminal.
(therefore, if you execute `brew list`, it does not matter, but if you do `brew list|less` (passed to less), then it shows above error message)

It may need to update `brew-file` before homebrew-2.6.0 is released.

---

On the other hand, if you use `stable` version (currently 2.5.12), it works with the latest brew-file (anyway, this is not related to the recent changes of brew-file).

Could you please check `brew version`?

It should be like:

```
$ brew version
Homebrew 2.5.12
Homebrew/linuxbrew-core (git revision 25561e; last commit 2020-11-29)
Homebrew/homebrew-cask (git revision 3b70e; last commit 2020-11-30)   
```

If it is like:

```
$ brew version
Homebrew 2.5.12-277-g9ee8cc9
Homebrew/linuxbrew-core (git revision 25561e; last commit 2020-11-29)
Homebrew/homebrew-cask (git revision 3b70e; last commit 2020-11-30)  
```

i.e., Homebrew's version has additional developper version after `2.5.12`,
then you are using master version.

This can happen if you set 

    export HOMEBREW_DEVELOPER=1

or if you called any of [developper subcommands](https://github.com/Homebrew/brew/tree/master/Library/Homebrew/dev-cmd) ever.
These commands can be checked by ** Built-in developer commands** list shown by `brew commands` .

Maybe you are not intended, but it happens sometime...
(Actually, my brew was also the master, I don't remember when I changed...)

The annoying problem is that once you set it,
there is no way to switch back by Homebrew's command...

If you want to return to the stable version, do:

* Check the status
```
$ cd $(brew --prefix)/Homebrew
$ git branch
* master
  stable
$ grep devccmdrun .git/config  
  devcmdrun = true 
```
If `devcmdrun = true` is set, it is change to master version at `brew update`.

* Return to the stable version
```
$ cd $(brew --prefix)/Homebrew
$ git checkout stable
$ git config  --unset homebrew.devcmdrun
```

* Check the status again
```
$ git branch
  master
* stable
$ grep devccmdrun .git/config  
$ brew version
Homebrew 2.5.12
Homebrew/linuxbrew-core (git revision 13a344; last commit 2020-11-29)
Homebrew/homebrew-cask (git revision 3b70e; last commit 2020-11-30)
```

Now `brew file update` should also work!

**Comment by zcutlip** [comment]
Yes that was the issue! I somehow got brew onto master. I'm not sure how since I've only had this MacBook a few weeks, but it's fixed now.

Thank you for the detailed instructions.
