### ISSUE TITLE
brew-file ignores 'cask' directive in Brewfile

### ISSUE THREAD

**Issue by zcutlip** [rcmdnk/homebrew-file#106]
When a cask is specified in the Brewfile, `brew-file` doesn't seem to explicitly pass `--cask` to `brew install`, so if there's a formula by the same name, that gets installed instead.

See example:

```Console
❱ cat brewfile.example
cask wireshark
❱ brew-file install -f ./brewfile.example
$ brew install --force wireshark
Warning: Treating wireshark as a formula. For the cask, use homebrew/cask/wireshark
```

This behavior happens with `brew file install` as well as `brew file update`. I'm not sure what happened, but I recently deleted my homebrew installation and reinstalled with `brew file install` and then I noticed the problem.

brew-file and brew version:
```
Homebrew 3.1.3
Homebrew/homebrew-core (git revision 553ca25a30; last commit 2021-04-22)
Homebrew/homebrew-cask (git revision d828331801; last commit 2021-04-22)
brew-file v8.3.4 16/Apr/2021
```

**Comment by rcmdnk** [comment]
Thanks for the report.
I assumed such overlaps were removed when `cask` command was removed, but not...

I added `--cask` option explicitly for cask installation in `brew file install`/`update`,
in version v3.8.5.

Could you please update brew-file and try it?

**Comment by zcutlip** [comment]
This is working great now. Thank you!
