### ISSUE TITLE
mas-cli on Monterey no longer supports "mas account" sub-command

### ISSUE THREAD

**Issue by sjames-au** [rcmdnk/homebrew-file#111]
Started migrating to Monterey.

mas-cli has indicated that api changes have removed the mas account capabilities of mas-cli (https://github.com/mas-cli/mas#%EF%B8%8F-known-issues)

resulting in:
```
$ brew file install
[ERROR]:
Please sign in to the App Store
```

```
$ mas account
Error: This command is not supported on this macOS version due to changes in macOS. For more information see: https://github.com/mas-cli/mas#known-issues
```

**Comment by rcmdnk** [comment]
Thanks for the report.
There seem some problems with mas for the recent macOS.

I did not understand the problem correctly
and recommended disabling mas by `--no_appstore`:
https://github.com/rcmdnk/homebrew-file/issues/110#issuecomment-964790230

but it seems most of other commands works
and the problem in brew-file is that 
it checks `mas account`.

It may take a long time to be fixed at mas side,
so I disable `mas account` check
and it should work if you sign in at App Store.app.

It should work at v8.5.8.

**Comment by rcmdnk** [comment]
keep seeing the problem @ #110
