### ISSUE TITLE
Wrong sha hash

### ISSUE THREAD

**Issue by otahontas** [rcmdnk/homebrew-file#122]
Newest commit (https://github.com/rcmdnk/homebrew-file/commit/e6ecf7cdf0c361823c8f7fbd51994ae10d85583c) apparently contains wrong sha256, it should be 1114a027bde7ab7b6eda9af7a5be17c8724e7dc953b9dbc283adb42d216e6642

**Comment by rcmdnk** [comment]
Thanks!
fixed (https://github.com/rcmdnk/homebrew-file/commit/1ccea7feecb9b64dad7ab5e00ea1a1081b2cf2d6)
