### ISSUE TITLE
Reinstall no longer supports --HEAD

### ISSUE THREAD

**Issue by hurricanehrndz** [rcmdnk/homebrew-file#127]
Running brew-file install results in an error because opts check
```
Error: invalid option: --HEAD
[ERROR]: Failed at command: /opt/homebrew/bin/brew reinstall neovim --HEAD
```

**Comment by rcmdnk** [comment]
Thanks for the report.

I think this happens when the Brewfile has different options for the packages already installed.

`reinstall` does not allow these options, then it should be done by `uninstall` and `install` commands.

v8.5.12 should fix this problem, please update brew-file and try it!

**Comment by hurricanehrndz** [comment]
Thank you, I will give it a shot.
