### ISSUE TITLE
use --installed-on-request option for brew leaves

### ISSUE THREAD

**Issue by rcmdnk** [rcmdnk/homebrew-file#129]
available from 3.2.0
[3.2.0 — Homebrew](https://brew.sh/2021/06/21/homebrew-3.2.0/)

**Comment by rcmdnk** [comment]
#75's update uses `installed_on_request` flag in `brew info` output
to identify these packages:
* Get package list by `brew leaves`
* Identify installed_on_request package from `brew info <package>`.
From 3.2.0, it can be done directly by `brew leaves --installed-on-request`.

Now I implemented it in v9.0.13.
It makes some commands a little bit faster.

**Comment by svdarren** [comment]
Thank you!  I'm switching laptops today and this gave me exactly what I needed.
