### ISSUE TITLE
"ImportError: No module named requests" on freshly installed Yosemite

### ISSUE THREAD

**Issue by rinopo** [rcmdnk/homebrew-file#17]
Hi,
Thank you very much for the useful tool!

On a freshly installed Yosemite, I get the above error on trying `brew file set_repo`.
Here is the gist showing what I did on Terminal.app just after a clean installation of OS 10.10.2:
https://gist.github.com/rinopo/12b6b29f0def98fb1531

Did I miss something?
Thanks!

**Comment by rcmdnk** [comment]
oops! I thought it is internal module, but "Requests" is external module, so you need to install it.
I added some introductions in README and when you run w/o Requests module.

If you want to create a repository from the command line, please install Requests:

    $ easy_install pip # in case you've not installed pip
    $ pip install requests

Otherswise, please make a repository directory in GitHub or other Git service.

**Comment by rinopo** [comment]
Thank you for the instruction!
