### ISSUE TITLE
Strange message "The cask file of Warning: nothing to list doesn't exist."

### ISSUE THREAD

**Issue by rinopo** [rcmdnk/homebrew-file#19]
Hi,
Please forgive me for posting multiple issues at a time.

If I have homebrew-cask brew-installed, but have nothing brew-cask-installed yet, I get the above warning when I do `brew file -i`.

I see it's not really a problem but kind of scary since the warning is printed in red bold letters and doesn't make sense :)

```shellsession
$ brew file -i
/Users/rinopo/.brewfile is already there.
Do you want to overwrite it? [y/n]: y
Ok, old input file was moved to /Users/rinopo/.brewfile.bak.
The cask file of Warning: nothing to list doesn't exist.
Please check later.



##################################
# Initialize /Users/rinopo/.brewfile
##################################

$ cat .brewfile 

# tap repositories and their packages

## caskroom/cask
tap caskroom/cask
install brew-cask

## rcmdnk/file
tap rcmdnk/file
install brew-file

# Below applications were installed by Cask,
# but don't not have corresponding casks.

#cask  install Warning: nothing to list
```

As a side note, 

> `# but don't not have corresponding casks.`

should be "do not have".

**Comment by rcmdnk** [comment]
Thank you for reporting.
The code was modified to suppress the message (and meaningless `cask install` line).

and thanks for noticing typo:sweat_smile:

**Comment by rinopo** [comment]
Thanks! :+1:
