### ISSUE TITLE
Add an option to ignore appstore apps

### ISSUE THREAD

**Issue by Packetslave** [rcmdnk/homebrew-file#22]
I run the same Homebrew setup, but different sets of App Store installed apps on different machines (I don't install Final Cut Pro on my laptop, for example).  This makes keeping a brewfile up-to-date quite difficult, as 'brew file update' will continually change the list of 'appstore' lines, depending on which machine it's run on.

**Comment by rcmdnk** [comment]
Thanks for the suggestion.
OK, I implemented "--no_appstore" option.

On the other hand, you can use additional brew file described in [homebrew-file/README.DETAILS.md at master · rcmdnk/homebrew-file](https://github.com/rcmdnk/homebrew-file/blob/master/README.DETAILS.md)

For example, add following line in your main Brewfile:

    file ~/.local_brewfile

and remove `Final Cut Pro`.

Then, make ~/.local_brewfile with a below line in the machine which needs Final Cut Pro:

    appstore Final Cut Pro

With this, `Final Cut Pro` will be managed in ~/.local_brewfile in the machine, 
and it is not mentioned in your laptop in which ~/.local_brewfile doesn't exist.

To use this feature, I just found a bug and updated brew-file.
Then, could you please update brew-file to the latest one (v3.5.11.
