### ISSUE TITLE
Doesn't know how to handle URL

### ISSUE THREAD

**Issue by nfarrar** [rcmdnk/homebrew-file#24]
Homebrew file chokes on the following:

    $ brew install https://raw.githubusercontent.com/moul/advanced-ssh-config/master/contrib/homebrew/assh.rb --HEAD

This adds the following to my brewfile:

    ## https:/
    tap https:/

**Comment by rcmdnk** [comment]
Thank you for the feedback.

I updated the script.
With the new script, `brew install https:...` will add new lines like:

    ## Direct install
    brew https://raw.githubusercontent.com/moul/advanced-ssh-config/master/contrib/homebrew/assh.rb --HEAD

On the other hand, there is one difficulty at `brew init`.
As long as I know, there is no way to know the original url of the installed formula in this way.
The formula is in `/Library/Caches/Homebrew/Formula/`, so only the script ca do is to distinguish from normal formulae.

So, in Brewfile,  it will be

    ## Direct install
    brew assh --HEAD

If you use only `brew install` and `brew uninstall` with brew-wrap,
then the URL will be kept.
