### ISSUE TITLE
brew reinstall

### ISSUE THREAD

**Issue by kyounger** [rcmdnk/homebrew-file#25]
I have brew-wrap working well when I do a `brew install xyz`, or even a `brew cask install xyz`, but recently I realized that my vim install didn't include lua interop, so I ran a `brew reinstall vim --with-lua` only to realize that it wasn't automatically added to my Brewfile.

Not sure if that's a bug or a feature :)

**Comment by rcmdnk** [comment]
Thank you for your feedback.
It is just because I didn't take reinstall into account.

The script has been updated and now (>= v3.7.0) `reinstall` is also supported.
