### ISSUE TITLE
Add option for specifying per-host directives

### ISSUE THREAD

**Issue by nfarrar** [rcmdnk/homebrew-file#29]
I keep my brewfile synchronized across multiple systems. There are a couple packages I install only one one machine and not the other.

It would be very helpful to be able to be able to do one of the following:

- specify the host for specific packages
- blacklist specific packages from being managed by homebrew-file
- specify that a certain package is optional (i.e. it's in brewfile, but user gets a prompt to select if it should actually be installed)
- some other option :)

**Comment by rcmdnk** [comment]
This can be done by using `file` line in Brewfile ([README.DETAILS](https://github.com/rcmdnk/homebrew-file/blob/master/README.DETAILS.md)

If you have a line like:

    file ./${HOST}.Brewfile

in Brewfile, then, a file with the current host name is read (this file's path can be absolute or relative to Brewfile).
You can have packages in ${HOST}.Brewfile only for the HOST.

If the corresponding file doesn't exist, it just ignores.

Does it satisfy your purpose?

**Comment by nfarrar** [comment]
Awesome, thank you! Trying it out, that should work.
