### ISSUE TITLE
Duplication of outdated casks.

### ISSUE THREAD

**Issue by MrJoy** [rcmdnk/homebrew-file#30]
`brew file casklist` has a tendency to produce duplicated items for outdated casks.  Not sure of the exact circumstances that cause it, but it seems to happen quite frequently to me.

E.G.

```
# There are new version for following applications.
cask install dockertoolbox
cask install dockertoolbox
cask install little-snitch
```

**Comment by rcmdnk** [comment]
I have found one bug about this and I think I could fix it.
Could you please try to update homebrew-file and casklist with new homebrew-file?

**Comment by MrJoy** [comment]
Your change appears to have fixed things.  Thank you!

**Comment by MrJoy** [comment]
Err, correction -- it has not fixed it.  (The generated file wound up in a different directory than I was expecting because of an error on my part.)  I've confirmed that the very latest available version of `brew-file` (as of a few minutes ago) was used.

**Comment by rcmdnk** [comment]
sorry, "latest" version (HEAD) has a trouble.
v3.7.7 (currently installed by normal brew install) should work for this problem.

**Comment by MrJoy** [comment]
When I type `brew update`, I only get v3.7.6.  I've tried untapping and re-tapping `rcmdnk/file` to no avail.

**Comment by MrJoy** [comment]
Ah!  Got it sorted out.  On v3.7.7, the issue is indeed fixed!
