### ISSUE TITLE
Persistent mis-identification when multiple casks define the same applications.

### ISSUE THREAD

**Issue by MrJoy** [rcmdnk/homebrew-file#31]
My `Caskfile` invariably winds up with this entry:

```
# Apps installed directly instead of by Cask in caskroom/versions
#cask install adobe-photoshop-cc-nl #/Applications/Utilities/Adobe Installers
```

I have the en-US version of Photoshop installed via the Creative Cloud Installer.  I presume this is because multiple formulae define that target path, and it's getting a hit on the first one it encounters?

**Comment by rcmdnk** [comment]
Yes, it writes only the first one which has a corresponding app.
I think there is no general way to find a language for each app.

If you installed the app by homebrew-cask, then a correct cask will be selected.

**Comment by MrJoy** [comment]
I didn't install it via Cask, I installed it via Creative Cloud and I would prefer to continue doing so.  Could you add an option to facilitate silencing this noise?

Or perhaps, check all formulae that match the location and indicate that the cask may be provided by one of those formulae?  Or even simply put a message noting that several formulae match that destination without listing which ones.

**Comment by rcmdnk** [comment]
It was updated to search for all casks for the corresponding app.

Though it could show wrong casks sometime (e.g. such `docker` has some additional casks like `docker-compose`, `docker-toolbox`, etc... and some of them can be found for these apps),
I think is it useful if it can show candidates as much as possible.
(I used `caskslist` especially to search for such an app which was directly installed but can be installed by Cask.)

**Comment by MrJoy** [comment]
You may consider breaking up the possible use-cases a bit here.

One use-case is to help with setting up a new workstation / keeping required software available on multiple machines a person works on.  To that end, being able to generate a "lockdown" file that doesn't have information like what's out of date, or what could be provided by casks is handy.

The ability to specify a list of non-cask-installed apps is also handy but would depend on individual workflows, I think.  I.E. that would need to remain optional for such a narrower workflow.

**Comment by rcmdnk** [comment]
Sorry, I'm not sure what you want.

Don't you need such AppStore app info. or System applications/directly installed info.?

`casklist` writes some **comments** for such possibilities,
and this is what I want to do with `casklist`,
because normal list is available by `brew file init`.

On the other hand you can use it in new machine as input.
In this time, brew-file just ignores these comments.
Therefore, I think there are no problem.

Or you can use `brew file init -f ./Brewfile_for_new_machine` to make normal Brewfile in new.

If you want to remove comments in Casklist,
then it may work for you:

    $ cat Caskfile |sed 's/#.*//'|grep -v "^$" > Casklist_wo_comments

**Comment by MrJoy** [comment]
The goal is to minimize noise while maximizing actionable information for the use-case of setting up a new machine, or bringing an existing machine up to date with a standard configuration.

Advisory information -- like the ability to install X via a cask when it has not been installed via cask -- is a nice report to have, but seems to me a separate use-case.

**Comment by rcmdnk** [comment]
I added `caskonly` option for such `init` sub-command.

You can make **clean** cask list by:

    $ brew file init -f ./Brewfile.caskonly --no_appstore --caskonly

This will list only casks and taps which is needed for casks.

How about this?
