### ISSUE TITLE
Inadequate escaping for incremental brewfile update.

### ISSUE THREAD

**Issue by MrJoy** [rcmdnk/homebrew-file#32]
App Store apps with quotes in the name have their quotes stripped when the hook for `brew install` runs, but the quoting is fine when `brew file init` / `brew file dump` are run.

**Comment by rcmdnk** [comment]
Could you please tell me any examples of such app?

**Comment by MrJoy** [comment]
* "Lock'n'Load"
* "Penny Arcade's On The Rain-Slick Precipice of Darkness 3"
* "Ships N' Battles"

**Comment by rcmdnk** [comment]
This also should be fixed at the current version (v3.7.8).

**Comment by MrJoy** [comment]
I can confirm that it appears to be fixed for me, thanks!
