### ISSUE TITLE
[Feature] Support Brew Pip

### ISSUE THREAD

**Issue by Derimagia** [rcmdnk/homebrew-file#33]
Brew Pip for managing Python Pips through Brew:
https://github.com/hanxue/brew-pip

Right now after installing a pip from brew-pip, it won't add to the Brewfile. When cleaning up, the pip will be removed from the system since it isn't in the Brewfile.

**Comment by rcmdnk** [comment]
Thanks for reporting.
Fixed at v3.7.9.
