### ISSUE TITLE
Hook brew-instal

### ISSUE THREAD

**Issue by tasuten** [rcmdnk/homebrew-file#36]
`brew install`と同様の動きをするサブコマンドのエイリアスに
`brew instal`(`l`が2つでなく1つ)があります。
https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/global.rb#L57

`etc/brew-wrap`ではこちらのエイリアスを使用した際はBrewfileが更新されないようなので
こちらのエイリアスを用いた際も更新されるようお願い致します。

**Comment by rcmdnk** [comment]
アップデートしてみました。
v3.9.2から`instal`でも自動更新される様になってると思います。

**Comment by tasuten** [comment]
アップデートありがとうございます。
この問題については解決を確認しました。
ありがとうございます。
以下の長文はその確認過程でちょっとハマったのでメモ書きとして残しておきます。

/*
具体的には`brew update && brew upgrade`や`brew reinstall rcmdnk/file/brew-file`のようにしても
`$(brew --prefix)/etc/brew-wrap`が古いバージョンのままのため、
v3.9.2からの変更が反映されないというものです。
ひとまずの解決策として`$(brew --prefix)/etc/brew-wrap`を`rm`などで削除の後、
`brew (re)install rcmdnk/file/brew-file`などを行うことで解決できると思います。
恐らくこれは
``` ruby
  # The directory where the formula's configuration files should be installed.
  # Anything using `etc.install` will not overwrite other files on e.g. upgrades
  # but will write a new file named `*.default`.
  # This directory is not inside the `HOMEBREW_CELLAR` so it is persisted
  # across upgrades.
``` 
 https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/formula.rb#L644

とあるので仕様っぽいですね…
一応このレポジトリ内での解決策としては
1. etc以外に置く
2. symlinkにする
3. brew-wrap.defaultがあればそっちを参照するようにする
とかがありそうです…
長文失礼しました…
*/

**Comment by rcmdnk** [comment]
情報有難うございます。
これ気づいてませんでした。

Formulaをアップデートして他ファイル同様シンボリックリンクとして扱う様にしました。

今のファイルを削除して作る様にもしてあるので、
`brew update && brew upgrade`してもらえばbrew-wrapがシンボリックリンクになり、
今後はきちんとアップデートされる様になるはずです。

**Comment by tasuten** [comment]
ありがとうございます。こちらでも問題なく動作致しました。
