### ISSUE TITLE
doesn't work with Python 3.x

### ISSUE THREAD

**Issue by nkmry** [rcmdnk/homebrew-file#37]
This doesn't work with Python 3.x.
I got some syntax errors.
Do you have a plan to support Python 3.x?

**Comment by rcmdnk** [comment]
Thank you for pointing it out.

The latest version of v3.11.1 should work with Python 3.5. (tested only with 3.5, but could work with other 3.x)
Could you please try it out?

**Comment by nkmry** [comment]
I installed v3.10.10 from Homebrew.
Now, because you updated brew-file.rb, I can install the latest version from Homebrew and it works in my environment.
Thanks! :+1:
