### ISSUE TITLE
'brew file init' loses install arguments

### ISSUE THREAD

**Issue by Packetslave** [rcmdnk/homebrew-file#39]
Frequently, when doing a 'brew file update', brew-file rewrites my Brewfile to lose install arguments. This seems to happen most frequently with emacs (losing --cocoa), git (losing --with-pcre) and vim (losing --override-system-vi)

```
❯ brew info emacs --installed
emacs: stable 24.5, devel 25.0.93, HEAD
GNU Emacs text editor
https://www.gnu.org/software/emacs/
/usr/local/homebrew/Cellar/emacs/24.5 (3,923 files, 109.5M) *
  Built from source on 2016-05-06 at 22:30:48 with: --with-cocoa
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/emacs.rb
==> Dependencies
[snip]


❯ grep emacs .brewfile
brew emacs --with-cocoa


❯ brew file init
/Users/blanders/.brewfile is already there.

######################################
# Initialize /Users/blanders/.brewfile
######################################


❯ grep emacs .brewfile
brew emacs

```

**Comment by rcmdnk** [comment]
Thank you for reporting.
It seems HOMEBREW changed its output of `brew info`, then brew-file fails to get option information every time.

I will update a.s.a.p., just a moment...

**Comment by rcmdnk** [comment]
brew-file was updated (v3.12.1).
It should write options correctly in Brewfile.

**Comment by Packetslave** [comment]
Seems like it fixed some (emacs, git) but not vim:

❯ grep vim .brewfile
brew vim --override-system-vi

❯ brew file update --no_appstore
$ command brew update
Already up-to-date.
$ command brew upgrade --all

######################################
# Initialize /Users/blanders/.brewfile
######################################

❯ grep vim .brewfile
brew vim

**Comment by rcmdnk** [comment]
Could you please check `brew info vim` output?

It should have a line like:

    Built from source on 2016-XX-XX at XX:XX:XX with: --override-system-vi

**Comment by Packetslave** [comment]
`❯ brew info vim --installed
vim: stable 7.4.1817, HEAD
Vi "workalike" with many additional features
http://www.vim.org/
Conflicts with: ex-vi
/usr/local/homebrew/Cellar/vim/7.4.1817 (1,689 files, 22.6M) *
  Built from source on 2016-05-08 at 11:17:07 with: --override-system-vi
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/vim.rb
==> Dependencies
Optional: lua ✘, luajit ✘
==> Options
--disable-nls
        Build vim without National Language Support (translated messages, keymaps)
--override-system-vi
        Override system vi
--with-client-server
        Enable client/server mode
--with-lua
        Build vim with lua support
--with-luajit
        Build with luajit support
--with-mzscheme
        Build vim with mzscheme support
--with-python3
        Build vim with python3 instead of python[2] support
--with-tcl
        Build vim with tcl support
--without-perl
        Build vim without perl support
--without-python
        Build vim without python support
--without-ruby
        Build vim without ruby support
--HEAD
        Install HEAD version`

**Comment by rcmdnk** [comment]
hmm... it seems brew has correct info.

ok, then could you please try again:

    $ brew update
    $ brew upgrade
    $ brew file init  --no_appstore

Then check if Brewfile has vim with option or not.
If it has, try

     $ brew file update --no_appstore

If it still has problem, could you please provide me information of:

     $ brew file version
     $ brew list

and current your Brewfile.

**Comment by Packetslave** [comment]
looks like that fixed it. thanks!
