### ISSUE TITLE
Support mas being installed through homebrew-core's mas

### ISSUE THREAD

**Issue by derimagia** [rcmdnk/homebrew-file#42]
Right now you seem to be using the repo "argon/mas/mas" for mas. At this point mas has been in homebrew's core list for a while now and can be installed using "brew install mas" without the custom tap. However when this is done, the list for App releases becomes empty:

"# App Store applications
appstore No installed apps found"

**Comment by rcmdnk** [comment]
Thank you for the information of mas.
I updated to use core's mas if it is not installed.

I updated my `mas` command by re-installing with core's formula, and I don't have any problem.

Could you please try `mas list` if it could give list or not.

I added checks not to list such a line if noe app sotre applications is installed,
but it seems you have some applications and the problem is different.

**Comment by derimagia** [comment]
Okay so it looks like there were 2 issues here. One was my fault - i was fixing the issue with mas itself with doing a mas list and when I was fixed it so "mas list" displayed something I kept trying to test it by running brew file cat instead of re-initing it. So the issue I reported is fixed.

But the actual issue that I was fixing with mas is the old issue with connecting to the user session when you are using tmux (See https://github.com/argon/mas#tmux https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard).

The fix they recommended is to wrap your entire tmux session in the wrapper but I don't like the overhead so I just alias what commands I need (So alias mas='reattach-to-user-namespace mas'). This doesn't work here and I can't do the same thing with brew since the "brew" wrapper calls "command brew" so it skips the alias.

For homebrew-file maybe you should just put this in the documentation? The only fix I can think about that could help this is if the command you  run "mas" was configuraable so I could say HOMEBREWFILE_MAS_COMMAND="reattach-to-user-namespace mas"?

**Comment by rcmdnk** [comment]
Thank you for the information.
I'm using GNU screen but I've not met the problem (although it seems it can happen in screen, and my screen doesn't have special patch for it, I think...)

Anyway, I can reproduce the problem in tmux.
It is easy to include `reattach-to-user-namespace` for `mas`,
so I included it in v3.13.1.

`mas` commands is renamed to `reattach-to-user-namespace mas` if you run in tmux.
If you don't have `reattach-to-user-namespace`, brew-file installs it automatically.

**Comment by derimagia** [comment]
LGTM. Thanks!

**Comment by derimagia** [comment]
Regarding screen, yeah I never needed it for screen - may be related to how apple patched screen... as well as actually in recent versions of mac I haven't needed the wrapper for pbcopy, or pbpaste.. (so i install reattach-to-use-namespace with --with-wrap-launchctl only...)
