### ISSUE TITLE
`brew file update`でXCodeがアンインストールされてしまう件について

### ISSUE THREAD

**Issue by k-tada** [rcmdnk/homebrew-file#43]
`brew file update`を実行すると、`git pull`の後に`sudo rm -rf /Applications/Xcode.app`が実行されてXcodeがアンインストールされてしまうのですが、これは意図した動作でしょうか？

また、この処理をスキップする方法があれば教えていただけないでしょうか？

よろしくお願いいたします。

**Comment by rcmdnk** [comment]
`brew file cat`などとしてBrewfileの中身を表示させた場合、
Xcodeは入っていますでしょうか？

もし入っていない場合、

    $ brew file init
    $ brew file push

をまず試してみてください。

その後、

    $ brew file update

をすればXcodeが消される事は無いと思います。

**Comment by k-tada** [comment]
迅速な回答ありがとうございます。
ご指摘の通り、BrewfileにXcodeが入ってなかったことが原因でした。
ご教示頂いた方法で無事解決いたしましたm(_ _)m
