### ISSUE TITLE
brew cask_upgradeでアップデートできない

### ISSUE THREAD

**Issue by km-tr** [rcmdnk/homebrew-file#48]
`brew cask info` で検索すると今インストールされているものより新しいバージョンが存在しているようなのですが、`brew cask_upgrade` を実行してもアップデートされないようです(1, 2週間ぐらい前から)。ご確認お願いします。

#### 例
[bitbar](https://github.com/caskroom/homebrew-cask/blob/master/Casks/bitbar.rb)

```
bitbar: 1.9.2
https://github.com/matryer/bitbar/
/usr/local/Caskroom/bitbar/1.6.0 (does not exist)
/usr/local/Caskroom/bitbar/1.7.0 (does not exist)
/usr/local/Caskroom/bitbar/1.9.0 (does not exist)
/usr/local/Caskroom/bitbar/1.9.1 (46 files, 1M)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/bitbar.rb
==> Name
BitBar
==> Artifacts
BitBar.app (app)
```

**Comment by rcmdnk** [comment]
この前あったcask側の変更の影響みたいです。（多分もうちょっと前からなっていたか、もしくは`brew cask info`の仕様だけちょっと前に変わったか）

治したものを3.16.1としてアップデートしました。

**Comment by rinopo** [comment]
関連？

> brew update
> をターミナルで実行しても「Already up-to-date.」と表示され続けていました。
> 「アップデートないのかな？」と、のほほんと構えていましたが、どうやら2016年8月10から11日の間に「brew update」を実行したユーザが遭遇しているバグのようで放っておいても直りません。
> 

[Homebrewでいくら「brew update」しても常に「Already up-to-date.」と表示される場合の解決策 - Macの手書き説明書](http://veadardiary.blog29.fc2.com/blog-entry-6264.html)

**Comment by km-tr** [comment]
3.16.1にしたところ `cask_upgrade` できるようになりました。ありがとうございます。

**Comment by rcmdnk** [comment]
ブログの方にちょっと詳しく書きましたが、原因は`brew cask info`の出力の変更です、一応。

> [Brew-fileのcask_upgradeをアップデート](http://rcmdnk.github.io/blog/2016/09/05/computer-mac-homebrew-brew-file/)
