### ISSUE TITLE
travis seems broken?

### ISSUE THREAD

**Issue by boneskull** [rcmdnk/homebrew-file#53]
PR-only issue?  [example](https://travis-ci.org/rcmdnk/homebrew-file/builds/162466353)

**Comment by boneskull** [comment]
Also, I'm unable to run CI on my own fork; looks like a missing pk or cert or something.  Can the build be self-signed?

**Comment by rcmdnk** [comment]
this is known and still i'm trying to solve it.
one of the problem is that I'm using encryption in travis job, and it seems not working for PR of others.
and now I have another trouble, too.
let me have a time...

**Comment by rcmdnk** [comment]
I think it has been fixed.
