### ISSUE TITLE
ZSH brew-wrap

### ISSUE THREAD

**Issue by giordanovi** [rcmdnk/homebrew-file#62]
Hi,
after adding the brew-wrap code to my .zshrc file, the terminal print this error message on new windows:
`_arguments:comparguments:313: can only be called from completion function`

**Comment by rcmdnk** [comment]
hmm... I could not reproduce the problem.
Could you please me zsh version?
My environment is:

    % sw_vers -productVersion
    10.12
    % brew --version
    Homebrew 1.0.6
    Homebrew/homebrew-core (git revision 5f95; last commit 2016-10-04)
    % brew-file --version
    brew-file v4.0.1 28/Sep/2016
    % zsh --version
    zsh 5.2 (x86_64-apple-darwin15.0.0)

At which command (or timing) do you have the error?

Could you please try w/o any settings but PATH and brew-wrap?

The error message seems related to completion,
though I have checked with zsh completion and didn't get anything wrong.

**Comment by giordanovi** [comment]
My enviroment is:

```
% sw_vers -productVersion
10.12

% brew --version
Homebrew 1.0.6
Homebrew/homebrew-core (git revision a12b9; last commit 2016-10-03)

% brew-file --version
brew-file v4.0.1 28/Sep/2016

% zsh --version
zsh 5.2 (x86_64-apple-darwin16.0)
```

I've the error on new terminal window or at cmq: `source ~/.zshrc`

**Comment by rcmdnk** [comment]
If you don't source brew-wrap in zshrc and source after your load zshrc,
does error happen when brew-wrap is sourced?

or what will happen if you load brew-wrap then source zshrc?

I think there is a conflict between your zshrc and brew-wrap, maybe ~
https://github.com/rcmdnk/homebrew-file/blob/master/etc/brew-wrap#L98

If you can give me a minimal zshrc which reproduce the problem, I can check it.
