### ISSUE TITLE
App Storeのアプリインストールで失敗する

### ISSUE THREAD

**Issue by hamaco** [rcmdnk/homebrew-file#73]
homebrew-file と mas を使用して App Store のアプリインストールしているのですが、最近のアプリの場合IDが10桁になっているようで、homebrew-file 内で9桁のIDかどうかのチェックをしている部分で弾かれてインストールに失敗してしまいます。

例えば Bear なんかが10桁のIDになっています。
https://itunes.apple.com/us/app/bear-beautiful-writing-app-for-notes-and-prose/id1091189122

**Comment by rcmdnk** [comment]
ありがとうございます。
調べてみると一昨年位に数を増やすために10桁も使い始めたみたいですね。

9桁のチェックをしてたのは、名前が数字から始まってるアプリを名前だけでBrewfileに書いた
様な状態を想定して、
名前に使われる数字は1桁か2桁が限度なので桁数をチェックしてたのですが、
9桁以上、としてしまってもおそらく問題ないので(9桁以上の数字から始まるアプリがなければ。。。そもそも9桁丁度の数字から始まれば今も問題にはなる可能性はありますが。)
そのように変更しました。

**Comment by hamaco** [comment]
ありがとうございます！ インストールできるの確認しましたー。
