### ISSUE TITLE
macOS 10.13 [beta] : Setting up a fresh install from existing Brewfile (GitHub)

### ISSUE THREAD

**Issue by raisedadead** [rcmdnk/homebrew-file#74]
```bash
$ brew file install
$ command brew tap caskroom/cask
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
Tapped 0 formulae (3,765 files, 4MB)
Password:
$ command brew install mas
mas: A full installation of Xcode.app 8.0 is required to compile this software.
Installing just the Command Line Tools is not sufficient.
Xcode can be installed from the App Store.
Error: An unsatisfied requirement failed this build.

Failed to install mas
```

**Comment by raisedadead** [comment]
Is there a way to skip installing `mas-cli` ?

**Comment by rcmdnk** [comment]
you can skip `mas-cli` if you remove `appstore` lines from Brewfile.
But you may want to use same Brewfile in new macOS, 
and `mas` seems not compatible with new macOS, yet.
ok, I changed to skip to install `mas-cli` instead of exiting when the installation fails,
as it could happen that `mas` will not be compatible even when it is released.

**Comment by raisedadead** [comment]
Thanks for getting back.

> you can skip mas-cli if you remove appstore lines from Brewfile.

I actually tried that by cleaning up my Brewfile and it did not work, confirming that `brew file install` command was tightly coupled to `mas-cli` somehow.

> ok, I changed to skip to install mas-cli instead of exiting when the installation fails,

So, this means that it will auto skip or I have to do anything aditional other than updating my install of `homebrew-file`?

> as it could happen that mas will not be compatible even when it is released.
Yes, you are right, but I have checked that their binary available in releases is compatible with my installtion.

Only building it up via homebrew is broken (an most probably will not be fixed as well).

I have requested support. Feel free to check
https://github.com/mas-cli/mas/issues/98

**Comment by rcmdnk** [comment]
> I actually tried that by cleaning up my Brewfile and it did not work, confirming that brew file install command was tightly coupled to mas-cli somehow.

ah, yes, it always uses mas-cli to check installed applications.

To skip this, you can use `--no_appstore` option.
This option skips any appstore related works (making list/installation)

> So, this means that it will auto skip or I have to do anything additional other than updating my install of homebrew-file?

yes, v4.1.17 skips mas installation if brew-file fails to install mas.
If you have `appstore` in your Brewfile (and don't use `--no_appstore),
brew-file will open AppStore.app to install applications.

> Only building it up via homebrew is broken (and most probably will not be fixed as well).

mas' formula requires xcode version 8.X. maybe macOS 10.13 has only 9.X or so.
maybe mas itself can be compiled with 9.X but Homebrew fails as 8.X can't be installed.
