### ISSUE TITLE
ENV vars no longer working for specifying additional files

### ISSUE THREAD

**Issue by kyounger** [rcmdnk/homebrew-file#78]
Steps to reproduce (using latest from tapped rcmdnk/file):

0. (Deleted all previous homebrew configuration)
1. `brew file init` to create new Brewfile with current config in `~/.config/brewfile/`
2. Add `file ./${HOST}.Brewfile` to the bottom of the created Brewfile
3. Move one of the `brew xxx` lines from Brewfile -> Host1.Brewfile
4. Ensure that the HOST env variable is exported in the env
5. Run `brew file update`

This seems to create a file in the same directory _literally_ named `${HOST}.Brewfile`, instead of picking up the configuration in the file named (for me) `home.Brewfile`.

**Comment by rcmdnk** [comment]
Thank you for the report.

I've updated brew-file to support environmental variables in Brewfile: v5.1.0.
Please try to update brew-file and do it.
