### ISSUE TITLE
brew-file might be incompatible with latest version of homebrew

### ISSUE THREAD

**Issue by stalinkay** [rcmdnk/homebrew-file#81]
@rcmdnk Hi, there seems to be an issue with brew-file possibly due to the latest homebrew update or something.

All commands seem to not be working with the latest version of homebrew.

Running `brew-file install; brew-file update` output nothing

**Comment by rcmdnk** [comment]
I just tried the latest Homebrew and confirm it works as expected.

My condition is:

    $ brew file --version
    Homebrew 1.5.14
    Homebrew/homebrew-core (git revision c33f; last commit 2018-04-09)
    brew-file v6.1.0 16/Mar/2018

**Comment by rcmdnk** [comment]
So, you are using developer version, right?

If you don't need it, could you please try to make it back to stable version
following this discussion?:
https://github.com/sportngin/brew-gem/pull/37

I will check with the developer version if I can make time,
but the developer version is sometimes so unstable that it doesn't deserve to test it as an end user...

**Comment by stalinkay** [comment]
@rcmdnk Thanks. That resolved it. I had to do the following:

```
$ git checkout stable
$ git config --file /usr/local/Homebrew/.git/config --unset homebrew.devcmdrun
$ brew update
```

**Comment by stalinkay** [comment]
@rcmdnk Closing
