### ISSUE TITLE
`brew-file update` is crashing

### ISSUE THREAD

**Issue by stalinkay** [rcmdnk/homebrew-file#83]
@znz `brew-file update` is failing on my end with the following stack trace. I have included my brew-file environment below. It was working just fine till I ran `brew-file update` about 2 days back.

### stack trace
```
Traceback (most recent call last):
  File "/usr/local/bin/brew-file", line 3340, in <module>
    main()
  File "/usr/local/bin/brew-file", line 3336, in main
    b.execute()
  File "/usr/local/bin/brew-file", line 2965, in execute
    self.get_list()
  File "/usr/local/bin/brew-file", line 1839, in get_list
    self.brewinfo.get_option(p, info[p])
  File "/usr/local/bin/brew-file", line 621, in get_option
    if len(installed["used_options"]) > 0:
KeyError: 'used_options'
```

### enviroment

```
Homebrew 1.8.6
Homebrew/homebrew-core (git revision 193b; last commit 2019-01-03)
Homebrew/homebrew-cask (git revision 6da8e; last commit 2019-01-04)
brew-file v6.1.6 19/Oct/2018
```

**Comment by rcmdnk** [comment]
Thank you for the report.
I updated brew-file to check if **used_options** is included in the package information (**installed**).
Please update brew-file to v6.1.7 or later.

On the other hand, I don't see any package which does not have **used_options**.
If possible, could you please show me your Brewfile, to check details?

**Comment by stalinkay** [comment]
> Thank you for the report.
> I updated brew-file to check if **used_options** is included in the package information (**installed**).
> Please update brew-file to v6.1.7 or later.
> 
> On the other hand, I don't see any package which does not have **used_options**.
> If possible, could you please show me your Brewfile, to check details?

Hi @rcmdnk thanks for the reply and quick update. I tested the update it appears to still be broken. Find attached my [Brewfile](https://github.com/rcmdnk/homebrew-file/files/2729365/Brewfile.txt).

`$ brew-file --version`

```
Homebrew 1.8.6
Homebrew/homebrew-core (git revision b22b6; last commit 2019-01-05)
Homebrew/homebrew-cask (git revision 71f93; last commit 2019-01-05)
brew-file v6.1.7 05/Jan/2019
```

**Comment by stalinkay** [comment]
@rcmdnk The error is different see below:

```
Traceback (most recent call last):
  File "/usr/local/bin/brew-file", line 3340, in <module>
    main()
  File "/usr/local/bin/brew-file", line 3336, in main
    b.execute()
  File "/usr/local/bin/brew-file", line 2965, in execute
    self.get_list()
  File "/usr/local/bin/brew-file", line 1839, in get_list
    self.brewinfo.get_option(p, info[p])
  File "/usr/local/bin/brew-file", line 624, in get_option
    if installed["version"] == v and k != "stable":
KeyError: 'version'
```

**Comment by rcmdnk** [comment]
Can you upload the result of:

     $ brew info --json=v1 --installed

?

**Comment by rcmdnk** [comment]
This result seems fine...

Could you please run [test-brew-file.txt](https://github.com/rcmdnk/homebrew-file/files/2729964/test-brew-file.txt) and show the result?

    $ chmod 755 test-brew-file.txt
    $ ./test-brew-file.txt update >& log

**Comment by stalinkay** [comment]
> This result seems fine...
> 
> Could you please run [test-brew-file.txt](https://github.com/rcmdnk/homebrew-file/files/2729964/test-brew-file.txt) and show the result?
> 
> ```
> $ chmod 755 test-brew-file.txt
> $ ./test-brew-file.txt update >& log
> ```

@stalinkay Find attached file. Had to rename it to .py to run. Find attached [log.txt](https://github.com/rcmdnk/homebrew-file/files/2730464/log.txt)

**Comment by rcmdnk** [comment]
Thanks.

The problem was made by **open-mpi** package.
Can you show the result of:

    $ ls -l $(brew --prefix)/opt/open-mpi
    $ ls -l $(brew --prefix)/Cellar/open-mpi

?

It may be better to check `brew doctor`.

On the other hand, new brew-file version v6.1.8 should work even in your case.

**Comment by stalinkay** [comment]
> Thanks.
> 
> The problem was made by **open-mpi** package.
> Can you show the result of:
> 
> ```
> $ ls -l $(brew --prefix)/opt/open-mpi
> $ ls -l $(brew --prefix)/Cellar/open-mpi
> ```
> ?
> 
> It may be better to check `brew doctor`.
> 
> On the other hand, new brew-file version v6.1.8 should work even in your case.

v6.1.8 appears to be playing nice, will let you know if something fails. I did `brew doctor` and it suggested I run `brew prune`. Thanks again. Find logs below:

```
$ ls -l $(brew --prefix)/opt/open-mpi
```

[log.txt](https://github.com/rcmdnk/homebrew-file/files/2730780/log.txt)


```
$ ls -l $(brew --prefix)/Cellar/open-mpi
```

[log2.txt](https://github.com/rcmdnk/homebrew-file/files/2730781/log2.txt)

**Comment by rcmdnk** [comment]
Thanks.

So, the problem is that installed **open-mpi** version is 4.0.0,
but it is registered (i.e. directory is created in Cellar) as **4.0.0.reinstal**.

Not sure if it is Homebrew's work or not,
but it may happen in other cases.

An additional update was added to the brew-file to manage such **XXX.reinstall** version.
The previous one works in most of the cases (which just picks up the first version in the installed array),
but the new one should pick up correct version even if the version is registered as **XXX.reinstall***.
