### ISSUE TITLE
Support private repositories in brew set_repo

### ISSUE THREAD

**Issue by radeksimko** [rcmdnk/homebrew-file#84]
Currently private repository is treated as "not found" during `brew set_repo`:

https://github.com/rcmdnk/homebrew-file/blob/90182462352ae727cd9d324dedc181ae0333c73c/bin/brew-file#L1185-L1192

It would be great if there was a way to set a private repo.

The only way around I'm aware of is to temporarily make the repo public, run `brew set_repo` and make it private.

**Comment by rcmdnk** [comment]
Thank you for the report.

Yes, it should be available for private repositories as now GitHub provides them in free!

The new version v7.0.1 should work for the private repository, please try it.

**Comment by radeksimko** [comment]
That was fast! Thanks for implementing it, I will give it a spin in upcoming day(s).
