### ISSUE TITLE
Brewfile gets reordered making it difficult to see what changed

### ISSUE THREAD

**Issue by zcutlip** [rcmdnk/homebrew-file#87]
I've found when I install or uninstall something causing my Brewfile to be rewritten, the list's order is not maintained. Items on the list often move around quite dramatically. This makes it hard to see via `git diff` what formula or cask has been added/removed.

I don't know if there's a `brew-file` setting to preserve Brewfile ordering. If not, I'd be happy to look into how to do this and submit a PR.

**Comment by zcutlip** [comment]
Upon closer inspection, it appears what happens is casks seem to move around. For example, in the Brewfile some casks will appear under `tap homebrew/cask` and others will appear under `# Other Cask applications`. 

But then later some of them will swap places so that something that was under `tap homebrew/cask` gets moved to the end under "other" or vice versa.

If I move all casks under `tap homebrew/cask` and remove the "other" section, next time the Brewfile gets written, that section returns at the bottom and some of the casks have been moved to it.

I spent some time looking at the code to determine what causes a given cask to get written out under `# Other Cask applications` but I haven't been able to work that out yet.

**Comment by rcmdnk** [comment]
Thanks for the report.
I could confirm that some of my histories show what you reported.
Even in my current Brewfile, some Cask applications which belong to homebrew/cask are placed under `Other Cask applications`.

It should be a bug, I will look into it.

**Comment by rcmdnk** [comment]
OK, I could fix it. (v7.0.3)

> [fix remove in for over list · rcmdnk/homebrew-file@f31fc98](https://github.com/rcmdnk/homebrew-file/commit/f31fc98979356f68935bc37eea2d008fefdd4c78)

It seems I fixed it for brew packages in 2016,
but did not touch cask list until now...

**Comment by zcutlip** [comment]
Awesome. Thanks for the quick update.

I think the formula is still installing 7.0.2, though, so I haven't been able to upgrade and test.

**Comment by rcmdnk** [comment]
Oops, sorry.
Now I updated the formula.

**Comment by zcutlip** [comment]
Great! Seems to work now. Thanks again!
