### ISSUE TITLE
brew file init Error

### ISSUE THREAD

**Issue by 0xmachos** [rcmdnk/homebrew-file#91]
OS: macOS `10.5.6`
Brew:  `2.5.0` (Homebrew/homebrew-core (git revision `6f4b92`; last commit 2020-09-11))
Shell: `zsh 5.8 (x86_64-apple-darwin19.3.0)`

When I run `brew file init` I get the following error:
```
$ brew file init -y
[ERROR]: Failed at command: git config --get github.user
```

This used to work for me and I'm not sure when it stopped working. 

I have a [`.gitconfig`](https://github.com/0xmachos/dotfiles/blob/master/.gitconfig) file which sets `user.name`. I've not seen `github.user` widely used before.

**Comment by rcmdnk** [comment]
Thank you for the report.
There was a bug to stop there,
but it should try to get `user.name` after `github.user`, too.

Could you please try v8.0.4 (do `brew update && brew upgrade && brew file init -y`)?
It will correctly try to get `user.name` after failing to get `github.user`.

**Comment by 0xmachos** [comment]
`v8.0.4` has fixed the issue for me. 

Cheers for the quick response and fix.
